# Generated by Django 4.2.7 on 2023-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='dis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
